theme: jekyll-theme-minimal
title: ğŸ’»ğŸğŸ“ğŸŒ
description: Shukhrat Mirrakhimov's CV
logo: [https://media-exp1.licdn.com/dms/image/C5103AQFr2mkqiyd7gA/profile-displayphoto-shrink_800_800/0/1580794557770?e=1619049600&v=beta&t=XJ0ih6_Pd2CZWFb3K-A7jautVxu62O9I3fPfTWn0StY]
